"""邮箱服务模块导出。"""

from .outlook_manager import (
    MailMethodOverview,
    MailboxConfig,
    MailboxDetailRequest,
    MailboxError,
    MailboxManager,
    MailboxOverview,
    MailboxQuery,
    MailboxServiceError,
    MessageDetail,
    MessageDetailRequest,
    MessageListRequest,
    MessageListResult,
    MessageSummary,
    MethodOverview,
    OutlookMailboxManager,
    ReadStateUpdateRequest,
    ReadStateUpdateResult,
    UpdateReadStateRequest,
    UpdateReadStateResult,
)

__all__ = [
    "MailMethodOverview",
    "MailboxConfig",
    "MailboxDetailRequest",
    "MailboxError",
    "MailboxManager",
    "MailboxOverview",
    "MailboxQuery",
    "MailboxServiceError",
    "MessageDetail",
    "MessageDetailRequest",
    "MessageListRequest",
    "MessageListResult",
    "MessageSummary",
    "MethodOverview",
    "OutlookMailboxManager",
    "ReadStateUpdateRequest",
    "ReadStateUpdateResult",
    "UpdateReadStateRequest",
    "UpdateReadStateResult",
]
